module.exports = {
  headers: [
    'playerName',
    'heroName',
    'damageDealt',
    'placeholder4',
    'placeholder5',
    'placeholder6',
    'placeholder7',
    'placeholder8',
    'placeholder9',
    'placeholder10',
    'placeholder11',
    'placeholder12',
    'placeholder13',
    'placeholder14',
    'placeholder15',
  ],
  stats: [
    {
      name: 'jarrett',
      hero: 'junkrat',
      damageDealt: 9253,
      placeholder4: 1,
      placeholder5: 1,
      placeholder6: 1,
      placeholder7: 1,
      placeholder8: 1,
      placeholder9: 1,
      placeholder10: 1,
      placeholder11: 1,
      placeholder12: 1,
      placeholder13: 1,
      placeholder14: 1,
      placeholder15: 1,
    },
    {
      name: 'james',
      hero: 'pharah',
      damageDealt: 8524,
      placeholder4: 1,
      placeholder5: 1,
      placeholder6: 1,
      placeholder7: 1,
      placeholder8: 1,
      placeholder9: 1,
      placeholder10: 1,
      placeholder11: 1,
      placeholder12: 1,
      placeholder13: 1,
      placeholder14: 1,
      placeholder15: 1,
    },
    {
      name: 'cody',
      hero: 'tracer',
      damageDealt: 6319,
      placeholder4: 1,
      placeholder5: 1,
      placeholder6: 1,
      placeholder7: 1,
      placeholder8: 1,
      placeholder9: 1,
      placeholder10: 1,
      placeholder11: 1,
      placeholder12: 1,
      placeholder13: 1,
      placeholder14: 1,
      placeholder15: 1,
    },
    {
      name: 'rami',
      hero: 'roadhog',
      damageDealt: 7300,
      placeholder4: 1,
      placeholder5: 1,
      placeholder6: 1,
      placeholder7: 1,
      placeholder8: 1,
      placeholder9: 1,
      placeholder10: 1,
      placeholder11: 1,
      placeholder12: 1,
      placeholder13: 1,
      placeholder14: 1,
      placeholder15: 1,
    },
    {
      name: 'victor',
      hero: 'hanzo',
      damageDealt: 6146,
      placeholder4: 1,
      placeholder5: 1,
      placeholder6: 1,
      placeholder7: 1,
      placeholder8: 1,
      placeholder9: 1,
      placeholder10: 1,
      placeholder11: 1,
      placeholder12: 1,
      placeholder13: 1,
      placeholder14: 1,
      placeholder15: 1,
    },
    {
      name: 'julian',
      hero: 'sombra',
      damageDealt: 8246,
      placeholder4: 1,
      placeholder5: 1,
      placeholder6: 1,
      placeholder7: 1,
      placeholder8: 1,
      placeholder9: 1,
      placeholder10: 1,
      placeholder11: 1,
      placeholder12: 1,
      placeholder13: 1,
      placeholder14: 1,
      placeholder15: 1,
    },
  ],
};
